homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret hassio_latitude
  longitude: !secret hassio_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
# Theme Based from @marcelhoffs https://community.home-assistant.io/t/midnight-theme/28598
  themes:
    midnight:
      # Main colors
      primary-color: '#5294E2'                                                        # Header
      accent-color: '#E45E65'                                                         # Accent color
      dark-primary-color: 'var(--accent-color)'                                       # Hyperlinks                                         
      light-primary-color: 'var(--accent-color)'                                      # Horizontal line in about
                                                                                  
      # Text colors                                                                  
      primary-text-color: '#b2b2b2'                                                   # Primary text colour, here is referencing dark-primary-color
      text-primary-color: 'var(--primary-text-color)'                                 # Primary text colour
      secondary-text-color: '#b2b2b2'                                                 # For secondary titles in more info boxes etc.
      disabled-text-color: '#7F848E'                                                  # Disabled text colour
      label-badge-border-color: 'green'                                               # Label badge border, just a reference value   

      # Background colors                                                            
      primary-background-color: '#383C45'                                             # Settings background
      secondary-background-color: '#383C45'                                           # Main card UI background  
      divider-color: 'rgba(0, 0, 0, .12)'                                             # Divider 
        
      # Table rows                                                                   
      table-row-background-color: '#353840'                                           # Table row
      table-row-alternative-background-color: '#3E424B'                               # Table row alternative
                                                                                  
      # Nav Menu                                                                   
      paper-listbox-color: 'var(--primary-color)'                                     # Navigation menu selection hoover
      paper-listbox-background-color: '#2E333A'                                       # Navigation menu background
      paper-grey-50: 'var(--primary-text-color)'                                   
      paper-grey-200: '#414A59'                                                       # Navigation menu selection
                                                                                  
      # Paper card                                                               
      paper-card-header-color: 'var(--accent-color)'                                  # Card header text colour
      paper-card-background-color: '#434954'                                          # Card background colour
      paper-dialog-background-color: '#434954'                                        # Card dialog background colour
      paper-item-icon-color: 'var(--primary-text-color)'                              # Icon color
      paper-item-icon-active-color: '#F9C536'                                         # Icon color active
      paper-item-icon_-_color: 'green'           
      paper-item-selected_-_background-color: '#434954'                               # Popup item select                      
      paper-tabs-selection-bar-color: 'green'

      # Labels 
      label-badge-red: 'var(--accent-color)'                                          # References the brand colour label badge border
      label-badge-text-color: 'var(--primary-text-color)'                             # Now same as label badge border but that's a matter of taste
      label-badge-background-color: '#2E333A'                                         # Same, but can also be set to transparent here

      # Switches
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'  

      # Sliders
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'

      # Google colors
      google-red-500: '#E45E65'
      google-green-500: '#39E949'

# Additional IP Address outside of Docker Container Used for Hassio 
http:
  base_url: !secret base_url_ip

websocket_api:

# iFrame Panels > Possible removal from Hassio
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:graphql
    url: !secret grafana_url
  sonarr:
    title: Sonarr
    icon: mdi:television-box
    url: !secret sonarr_url
  radarr:
    title: Radarr
    icon: mdi:filmstrip
    url: !secret radarr_url
  nzbget:
    title: NZBGet
    icon: mdi:download
    url: !secret nzbget_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Nabu Casa Cloud Component $5 per month - https://www.nabucasa.com/
cloud:
  google_actions:
    filter:
      include_entities:
        - switch.home_server
        - switch.home_desktop
        - switch.office_lock
        - switch.christmas_lights
        - climate.landing_temperature
        - climate.bathroom_temperatur

# Nest Integration 
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

# Enables configuration UI
config:

# Text to speech
tts:
  - platform: google

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sensor
      - media_player

# Track the sun
sun:

# Database
recorder:
  purge_interval: 2
  purge_keep_days: 5

# Google Hangouts Notify Platform
notify:
  - name: noodlemctwoodle
    platform: hangouts
    default_conversations:
      - id: !secret notifier_noodlemctwoodle
      - name: HA Main

# Prometheus DB Comfiguration
prometheus:
  namespace: !secret prometheus_scrape_name

# Climate > To be removed
climate:
  - platform: generic_thermostat
    name: Landing Temperature 
    heater: switch.demo1
    target_sensor: sensor.landing_temperature
  - platform: generic_thermostat
    name: Bathroom Temperature 
    heater: switch.demo1
    target_sensor: sensor.bathroom_temperature

# Dark Sky Weather API for LoveLaceUI
weather:
  - platform: darksky
    api_key: !secret dark_sky_api

# Azure Image Processing > In Testing
# image_processing:
#  - platform: microsoft_face_detect
#    source:
#      - entity_id: camera.front_door

# Azure Image Processing > In Testing
#microsoft_face:
#  api_key: !secret microsoft_face_api
#  azure_region: !secret microsoft_face_region
  

# Single File Configs
group: !include groups.yaml
script: !include scripts.yaml

## Custom Includes ##

#### /custom_config/notify/ ####
hangouts: !include custom_config/notify/hangouts.yaml
#### /custom_config/network/ ####
device_tracker: !include custom_config/network/device_tracker.yaml
shell_command: !include custom_config/network/shell_commands.yaml
zone: !include custom_config/network/zones.yaml


## Custom Include Directories ## 

#### /custom_config/automations/ ####
automation: !include_dir_merge_list custom_config/automations
#### /custom_config/hue_lights/ ####
light: !include_dir_merge_list custom_config/hue_lights
#### /custom_config/media_player/ ####
media_player: !include_dir_merge_list custom_config/media_player
#### /custom_config/intents/ ####
intent_script: !include_dir_merge_list custom_config/intents
#### /custom_config/sensors/ ####
sensor: !include_dir_merge_list custom_config/sensors
#### /custom_config/switch/ ####
switch: !include_dir_merge_list custom_config/switch